server:
  port: 8761 # Default port for Eureka dashboard

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # Do not register self as client
    fetch-registry: false       # Do not fetch registry from others 